# Generated by Django 2.1.1 on 2018-09-28 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activation_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_id', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=200)),
                ('content', models.CharField(max_length=200)),
                ('sent_date', models.DateTimeField(verbose_name='Time sent')),
                ('verify_id', models.CharField(max_length=50)),
                ('escalation_level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Response_Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_id', models.IntegerField()),
                ('sent_date', models.DateTimeField(verbose_name='Time sent')),
                ('location_coord', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='EscalationLevel',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.AddField(
            model_name='nurse',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='nurse',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nurse',
            name='associated_activations',
            field=models.ManyToManyField(related_name='assoc_activations', to='activation.Activation_Message'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='associated_responses',
            field=models.ManyToManyField(related_name='assoc_responses', to='activation.Response_Message'),
        ),
    ]
