# Generated by Django 2.1.1 on 2018-09-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0003_auto_20180928_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='activation_message',
            name='sent_success',
            field=models.BooleanField(default=False, verbose_name='Sent Success'),
        ),
    ]
