# Generated by Django 2.1.1 on 2018-09-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0005_auto_20180928_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nurse',
            name='phone_carrier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Telus'), (2, 'Rogers'), (3, 'Bell'), (4, 'Shaw'), (5, 'Fido'), (6, 'Koodo'), (7, 'Virgin'), (8, 'Chatr')]),
        ),
    ]
