# Generated by Django 2.1.1 on 2018-09-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0006_auto_20180929_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='nurse',
            name='user_id',
            field=models.CharField(default='xxx@viha.ca', max_length=50),
            preserve_default=False,
        ),
    ]
