# Generated by Django 2.1.1 on 2018-09-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0008_auto_20180929_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.IntegerField()),
                ('start_time', models.DateTimeField(verbose_name='Shift start')),
                ('end_time', models.DateTimeField(verbose_name='Shift end')),
                ('nurse', models.ManyToManyField(related_name='nurse', to='activation.Nurse')),
            ],
        ),
    ]
