# Generated by Django 2.1.1 on 2018-09-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0009_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='response_message',
            name='activation',
            field=models.ManyToManyField(related_name='activation', to='activation.Activation_Message'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='associated_activations',
            field=models.ManyToManyField(blank=True, related_name='assoc_activations', to='activation.Activation_Message'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='associated_responses',
            field=models.ManyToManyField(blank=True, related_name='assoc_responses', to='activation.Response_Message'),
        ),
        migrations.AlterField(
            model_name='nurse',
            name='phone_carrier',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Telus'), (2, 'Rogers'), (3, 'Bell'), (4, 'Fido'), (5, 'Koodo'), (6, 'Virgin'), (7, 'Chatr')]),
        ),
    ]
