# Generated by Django 2.1.1 on 2018-09-29 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0010_auto_20180929_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='response_message',
            name='reponse_success',
            field=models.BooleanField(default=False, verbose_name='Response Success'),
        ),
    ]
