# Generated by Django 2.1.1 on 2018-09-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0011_response_message_reponse_success'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response_message',
            old_name='reponse_success',
            new_name='response_success',
        ),
    ]
