# Generated by Django 2.1.1 on 2018-09-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0013_response_message_response_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='activation_message',
            name='escalation_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'No escalation'), (1, 'Repeat activation'), (2, 'Contact coordinator'), (3, 'Repeat coordinator'), (4, 'Contact all regions')]),
        ),
    ]
