# Generated by Django 2.1.1 on 2018-09-29 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activation', '0014_auto_20180929_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activation_message',
            name='sent_success',
        ),
        migrations.AddField(
            model_name='activation_message',
            name='responded',
            field=models.BooleanField(default=False, verbose_name='Responded Success'),
        ),
        migrations.AddField(
            model_name='nurse',
            name='region',
            field=models.PositiveSmallIntegerField(choices=[(1, 'A - Port Hardy'), (2, 'B - Campbell River'), (3, 'C - Nanaimo'), (4, 'D - Victoria')], null=True),
        ),
    ]
